#!/bin/sh
# mansite
# shellcheck disable=SC2317

VERSION='2.0.7'

mansite_main() {
	trap _exit INT TERM

	E_ARGS=16
	E_FAILED_CD=17
	E_NO_MIDDLEMAN=18
	E_EXISTS=19

	SCRIPT_INV="$( basename "$0" )"
	SCRIPT_PATH="$( readlink -f "$0" )"
	SCRIPT_NAME="$( basename "$SCRIPT_PATH" )"
	SCRIPT_DIR="$( dirname "$SCRIPT_PATH" )"

	BUILD=0

	while getopts bhv opt
	do
		case $opt in
			b) BUILD=1 ;;
			h) CMD=help ;;
			v) CMD=version ;;
			*) _invalid_opt ;;
		esac
	done

	shift "$(( OPTIND - 1 ))"

	[ $# -gt 0 ] && CMD="$1" && shift
	[ -z "$CMD" ] && CMD="serve"

	case "$CMD" in
		mm) CMD=middleman ;;
	esac

	case "$CMD" in
		build|deploy|help|middleman|new|serve|version) "mansite_$CMD" "$@" ;;
		*) _invalid_cmd ;;
	esac

	_exit
}

mansite_help() {
cat <<USAGE
$SCRIPT_NAME $VERSION

USAGE: $SCRIPT_INV [<options>] <command> [<args>...]

Serve or build site using Middleman.

COMMANDS:

	build [<env>]
		Build site using Middleman. Defaults to production environment.

	deploy [<env>]
		Deploy site using Middleman. Defaults to production environment.

	help
		Show this help message.

	middleman [<args>]
		Run Middleman. Pass all arguments to it.

	mm [<args>]
		Alias for 'middleman'.

	new <dir>
		Create new mansite in <dir>.

	serve [<args>]
		Serve this site using Middleman. Pass arguments to it.

	version
		Show the version.

OPTIONS:

	-b        Build before deploy.
	-h        Show this help screen.
	-v        Show script name and version number.

USAGE
}

mansite_build() {
	env_name="$1"
	[ -z "$env_name" ] && env_name=production
	rake "build:$env_name"
}

mansite_deploy() {
	env_name="$1"
	[ -z "$env_name" ] && env_name=production
	[ "$BUILD" -ne 0 ] && ( mansite_build "$env_name" || return $? )
	rake "deploy:$env_name"
}

mansite_middleman() {
	_find_middleman_dir
	[ "$( pwd )" != "$middleman_dir" ] && _echo "$middleman_dir"
	cd "$middleman_dir" || exit "$E_FAILED_CD"
	[ $# -gt 0 ] && bundle exec middleman "$@" && return
	bundle exec middleman "$@"
}

mansite_new() {
	[ $# -lt 1 ] && _fatal "$E_ARGS" "Must specify directory."

	dir="$1"
	[ -d "$dir" ] && _fatal "$E_EXISTS" "Directory already exists: $dir"

	git clone https://github.com/remino/mansite "$dir"
	cd "$dir" || _fatal "$E_FAILED_CD" "Failed to cd to: $dir"
	[ -d .git ] && rm -rf .git
	npm install
	bundle install
	git init
	git add .
	git commit -m "Initial commit."
}

mansite_serve() {
	mansite_middleman "$@"
}

mansite_version() {
	_echo "$SCRIPT_NAME $VERSION"
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_exit() {
	exit_code=$?
	exit $exit_code
}

_fatal() {
	exit_code="$1"
	shift
	_error "$@"
	exit "$exit_code"
}

_find_middleman_dir() {
	for middleman_dir in "$( pwd )" "$SCRIPT_DIR"
	do
		while [ "$middleman_dir" != '/' ]
		do
			[ -f "$middleman_dir/config.rb" ] && return
			middleman_dir="$( dirname "$middleman_dir" )"
		done
	done

	_fatal "$E_NO_MIDDLEMAN" "Failed to find Middleman directory"
}

_invalid_cmd() {
	_error "Invalid command: $CMD"
	_echo
	mansite_help
	exit "$E_ARGS"
}

_invalid_opt() {
	_error "Invalid option: $opt"
	_echo
	mansite_help
	exit "$E_ARGS"
}

mansite_main "$@"
