#!/bin/sh
# mansite
# shellcheck disable=SC2317

VERSION='1.1.0'

mansite_main() {
	trap _exit INT TERM

	e_args=16
	e_failed_cd=17
	e_no_middleman=18
	e_exists=19

	scriptinv="$( basename "$0" )"
	scriptpath="$( readlink -f "$0" )"
	scriptname="$( basename "$scriptpath" )"
	scriptdir="$( dirname "$scriptpath" )"

	while getopts hv opt
	do
		case $opt in
			h) cmd=help ;;
			v) cmd=version ;;
			*) _invalid_opt ;;
		esac
	done

	shift "$(( OPTIND - 1 ))"

	[ $# -gt 0 ] && cmd="$1" && shift
	[ -z "$cmd" ] && cmd="serve"

	case "$cmd" in
		build|help|middleman|new|serve|version) "mansite_$cmd" "$@" ;;
		*) _invalid_cmd ;;
	esac

	_exit
}

mansite_help() {
cat <<USAGE
$scriptname $VERSION

USAGE: $scriptinv [<options>] <command> [<args>...]

Serve or build site using Middleman.

COMMANDS:

	build
		Build site using Middleman. Pass arguments to it.

	help
		Show this help message.

	middleman [<args>]
		Run Middleman. Pass all arguments to it.

	new <dir>
		Create new mansite in <dir>.

	serve [<args>]
		Serve this site using Middleman. Pass arguments to it.

	version
		Show the version.

OPTIONS:

	-h        Show this help screen.
	-v        Show script name and version number.

USAGE
}

mansite_build() {
	rake build:production
}

mansite_middleman() {
	_find_middleman_dir
	[ "$( pwd )" != "$middleman_dir" ] && _echo "$middleman_dir"
	cd "$middleman_dir" || exit "$e_failed_cd"
	[ $# -gt 0 ] && bundle exec middleman "$@" && return
	bundle exec middleman "$@"
}

mansite_new() {
	[ $# -lt 1 ] && _fatal "$e_args" "Must specify directory."

	dir="$1"
	[ -d "$dir" ] && _fatal "$e_exists" "Directory already exists: $dir"

	git clone https://github.com/remino/mansite "$dir"
	cd "$dir" || _fatal "$e_failed_cd" "Failed to cd to: $dir"
	[ -d .git ] && rm -rf .git
	bundle install
	git init
	git add .
	git commit -m "Initial commit."
}

mansite_serve() {
	rake serve
}

mansite_version() {
	_echo "$scriptname $VERSION"
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_exit() {
	exit_code=$?
	exit $exit_code
}

_fatal() {
	exit_code="$1"
	shift
	_error "$@"
	exit "$exit_code"
}

_find_middleman_dir() {
	for middleman_dir in "$( pwd )" "$scriptdir"
	do
		while [ "$middleman_dir" != '/' ]
		do
			[ -f "$middleman_dir/config.rb" ] && return
			middleman_dir="$( dirname "$middleman_dir" )"
		done
	done

	_fatal "$e_no_middleman" "Failed to find Middleman directory"
}

_invalid_cmd() {
	_error "Invalid command: $cmd"
	_echo
	mansite_help
	exit $e_args
}

_invalid_opt() {
	_error "Invalid option: $opt"
	_echo
	mansite_help
	exit $e_args
}

mansite_main "$@"
